version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/api/auth/approle"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/api/auth/kubernetes"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/api/auth/ldap"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/api/auth/userpass"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/sdk"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
