name: test-run-go-tests-for-path

on:
  workflow_call:
    inputs:
      name:
        description: 'The name to use that will appear in the output log file artifact'
        required: true
        type: string
      path:
        description: 'The path to the test without the precedeing "./" or following "/..." e.g. go test -v ./$path/...'
        required: true
        type: string
    # We will need to add the capacity for receiving passed secrets once we get to the tests that require API credentials

env:
  VAULT_ACC: 1

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ./.github/actions/set-up-go
      - run: go test -v ./${{ inputs.path }}/... 2>&1 | tee ${{ inputs.name }}.txt
      - uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        with:
          name: ${{ inputs.name }}-output
          path: ${{ inputs.name }}.txt
          retention-days: 2
